# Generated by Django 5.1.1 on 2026-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
