# Generated by Django 5.1.1 on 2026-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wholesale_price',
            field=models.FloatField(blank=True, help_text='Wholesale/bulk price per unit (leave blank to use retail price)', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(help_text='Retail price per unit'),
        ),
    ]
