# Generated by Django 5.1.1 on 2026-02-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_wholesale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_description',
        ),
    ]
