# Generated by Django 5.1.1 on 2026-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity_per_box',
            field=models.PositiveIntegerField(default=1, help_text='Number of units per box for wholesale'),
        ),
        migrations.AlterField(
            model_name='products',
            name='wholesale_price',
            field=models.FloatField(blank=True, help_text='Wholesale unit price per item in a box (leave blank to default to ₵200)', null=True),
        ),
    ]
