# Generated by Django 5.1.1 on 2026-02-28 13:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_quantity_per_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional short product video', max_length=255, null=True, verbose_name='video'),
        ),
    ]
