# Generated by Django 5.1.1 on 2026-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wholesale_stock',
            field=models.IntegerField(default=0, help_text='Number of full boxes available for wholesale'),
        ),
    ]
